# 1. Basic Arrays

In this notebook, we will learn the basics of NumPy arrays, including:
1. **Array Creation**: How to create arrays.
2. **Array Attributes**: Checking the properties of an array.
3. **Random Number Generation**: Creating arrays with random numbers.

In [5]:
import numpy as np

## 1.1 Array Creation
Here are some built-in NumPy functions to create arrays:

In [6]:
# 1. Create an array from a Python list (np.array)
arr = np.array([1, 2, 3, 4, 5])
print("np.array:\n", arr)

np.array:
 [1 2 3 4 5]


In [7]:
# 2. Array filled with zeros (np.zeros)
zeros = np.zeros((2, 3)) # 2 rows, 3 columns matrix
print("np.zeros:\n", zeros)

np.zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [8]:
# 3. Array filled with ones (np.ones)
ones = np.ones((3, 2))
print("np.ones:\n", ones)

np.ones:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]


In [9]:
# 4. Array with evenly spaced values within a given interval (np.arange)
arange = np.arange(0, 10, 2) # start=0, stop=10, step=2
print("np.arange:\n", arange)

np.arange:
 [0 2 4 6 8]


In [10]:
# 5. Array with evenly spaced numbers over a specified interval (np.linspace)
linspace = np.linspace(0, 1, 5) # 5 evenly spaced numbers from 0 to 1
print("np.linspace:\n", linspace)

np.linspace:
 [0.   0.25 0.5  0.75 1.  ]


## 1.2 Array Attributes
Every NumPy array has built-in attributes to check its dimensions, size, and data type.

In [11]:
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print("Matrix:\n", matrix)

print("\n--- Attributes ---")
print("Shape (rows, columns):", matrix.shape)
print("Size (total elements) :", matrix.size)
print("Ndim (number of dimensions):", matrix.ndim)
print("Dtype (data type)    :", matrix.dtype)

Matrix:
 [[1 2 3]
 [4 5 6]]

--- Attributes ---
Shape (rows, columns): (2, 3)
Size (total elements) : 6
Ndim (number of dimensions): 2
Dtype (data type)    : int64


## 1.3 Random Number Generation
Often, we need dummy data containing random numbers. The `np.random` module provides this.

In [12]:
# Random numbers from a uniform distribution [0, 1)
rand_arr = np.random.rand(2, 2)
print("Random (0-1):\n", rand_arr)

# Random integers (start, stop, size)
randint_arr = np.random.randint(0, 10, size=(3, 3))
print("\nRandom Integer (0-9):\n", randint_arr)

# Standard Normal Distribution (mean=0, std=1)
randn_arr = np.random.randn(3)
print("\nRandom Normal:\n", randn_arr)

Random (0-1):
 [[0.37548736 0.61818769]
 [0.08187409 0.94597588]]

Random Integer (0-9):
 [[1 5 4]
 [5 4 8]
 [4 0 6]]

Random Normal:
 [ 1.97975124 -0.35002083 -1.56036195]
