# 1. Basic Arrays

In this notebook, we will learn the basics of NumPy arrays, including:
1. **Array Creation**: How to create arrays.
2. **Array Attributes**: Checking the properties of an array.
3. **Random Number Generation**: Creating arrays with random numbers.

In [28]:
import numpy as np

## 1.1 Array Creation
Here are some built-in NumPy functions to create arrays:

In [29]:
# 1. Create an array from a Python list (np.array)
arr = np.array([1, 2, 3, 4, 5])
print("np.array:\n", arr)

np.array:
 [1 2 3 4 5]


In [30]:
# 2. Array filled with zeros (np.zeros)
zeros = np.zeros((2, 3)) # 2 rows, 3 columns matrix
print("np.zeros:\n", zeros)

np.zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [31]:
# 3. Array filled with ones (np.ones)
ones = np.ones((3, 2))
print("np.ones:\n", ones)

np.ones:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]


In [32]:
# 4. Array with evenly spaced values within a given interval (np.arange)
arange = np.arange(0, 10, 2) # start=0, stop=10, step=2
print("np.arange:\n", arange)

np.arange:
 [0 2 4 6 8]


In [33]:
# 5. Array with evenly spaced numbers over a specified interval (np.linspace)
linspace = np.linspace(0, 1, 5) # 5 evenly spaced numbers from 0 to 1
print("np.linspace:\n", linspace)

np.linspace:
 [0.   0.25 0.5  0.75 1.  ]


In [34]:
# 6. Array filled with a constant value (np.full)
full_arr = np.full((2, 3), 7) # 2x3 matrix filled with 7
print("np.full:\n", full_arr)

np.full:
 [[7 7 7]
 [7 7 7]]


In [35]:
# 7. Identity matrix (np.eye)
identity = np.eye(3) # 3x3 identity matrix (1s on diagonal, 0s elsewhere)
print("np.eye:\n", identity)

np.eye:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## 1.2 Array Attributes
Every NumPy array has built-in attributes to check its dimensions, size, and data type.

In [36]:
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print("Matrix:\n", matrix)

print("\n--- Attributes ---")
print("Shape (rows, columns):", matrix.shape)
print("Size (total elements) :", matrix.size)
print("Ndim (number of dimensions):", matrix.ndim)
print("Dtype (data type)    :", matrix.dtype)

Matrix:
 [[1 2 3]
 [4 5 6]]

--- Attributes ---
Shape (rows, columns): (2, 3)
Size (total elements) : 6
Ndim (number of dimensions): 2
Dtype (data type)    : int64


## 1.3 Random Number Generation
Often, we need dummy data containing random numbers. The `np.random` module provides this.

In [37]:
# Random numbers from a uniform distribution [0, 1)
rand_arr = np.random.rand(2, 2)
print("Random (0-1):\n", rand_arr)

# Random integers (start, stop, size)
randint_arr = np.random.randint(0, 10, size=(3, 3))
print("\nRandom Integer (0-9):\n", randint_arr)

# Standard Normal Distribution (mean=0, std=1)
randn_arr = np.random.randn(3)
print("\nRandom Normal:\n", randn_arr)

Random (0-1):
 [[0.15601864 0.15599452]
 [0.05808361 0.86617615]]

Random Integer (0-9):
 [[3 7 7]
 [2 5 4]
 [1 7 5]]

Random Normal:
 [ 1.46237812  1.53871497 -2.43910582]


**Reproducibility (Setting a Seed)**
To get the same random numbers every time you run the code, you can set a seed.

In [38]:
np.random.seed(42) # The number 42 is arbitrary
print("Seeded random:\n", np.random.rand(2))

Seeded random:
 [0.37454012 0.95071431]


**Random Choice**
You can also pick random elements from an existing array or list.

In [39]:
choices = ["apple", "banana", "cherry", "date"]
random_choice = np.random.choice(choices, size=2, replace=False)
print("Random choice:\n", random_choice)

Random choice:
 ['banana' 'date']


## 1.4 Array Manipulation
Two very common and essential operations are changing the shape of an array and changing its data type.

**1. Reshaping Arrays (`arr.reshape`)**
Reshaping is highly used when preparing data for **Machine Learning models** (e.g., converting a flat 1D array of pixels into a 2D image matrix).

In [40]:
# Create a 1D array with 12 elements
arr_flat = np.arange(12)
print("Original 1D array:\n", arr_flat)

# Reshape into a 2D array (3 rows, 4 columns)
# Note: The total number of elements must remain the same (3 * 4 = 12)
arr_2d = arr_flat.reshape(3, 4)
print("\nReshaped to 3x4 matrix:\n", arr_2d)

Original 1D array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped to 3x4 matrix:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


**2. Type Casting (`arr.astype`)**
Changing data types is extremely useful for **saving memory** (e.g., converting `float64` to `float32`) or when an algorithm strictly requires integers.

In [41]:
# Array of floating point numbers
arr_float = np.array([1.9, 2.5, 3.1])
print("Float array:", arr_float)
print("Data type:", arr_float.dtype)

# Cast to integers (this truncates the decimals, it does NOT round)
arr_int = arr_float.astype(int)
print("\nInteger array:", arr_int)
print("New Data type:", arr_int.dtype)

Float array: [1.9 2.5 3.1]
Data type: float64

Integer array: [1 2 3]
New Data type: int64


**3. Flattening Arrays (`arr.flatten`)**
Flattening is the opposite of reshaping. It converts a multi-dimensional array into a 1D array. This is frequently used when feeding image data or matrices into a Machine Learning model that expects a flat list of numbers.

In [42]:
# Let's use a 2D matrix
matrix_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("Original 2D Matrix:\n", matrix_2d)

# Flatten it to 1D
flat_arr = matrix_2d.flatten()
print("\nFlattened 1D Array:", flat_arr)

Original 2D Matrix:
 [[1 2 3]
 [4 5 6]]

Flattened 1D Array: [1 2 3 4 5 6]


**4. Copying Arrays (`arr.copy`)**
In NumPy, assigning an array to a new variable or slicing it often creates a **view** (a reference), NOT a new copy in memory. If you change the view, the original data changes! Using `.copy()` ensures you create a safe, independent duplicate.

In [43]:
original = np.array([10, 20, 30])

# ❌ WRONG WAY (Creates a reference / view)
reference = original
reference[0] = 99
print("Original after modifying reference:", original) # Original is modified!

# Reset the original
original = np.array([10, 20, 30])

# ✅ CORRECT WAY (Creates an independent copy)
safe_copy = original.copy()
safe_copy[0] = 99
print("\nOriginal after modifying safe copy:", original) # Original stays safe!
print("Safe copy:", safe_copy)

Original after modifying reference: [99 20 30]

Original after modifying safe copy: [10 20 30]
Safe copy: [99 20 30]
