# 1. Basic Arrays

In this notebook, we will learn the fundamentals of NumPy arrays, starting from how to create them to how to manipulate their shapes and types.

We will cover:
1. **Array Creation**: How to create arrays using `np.array`, `np.zeros`, `np.ones`, `np.full`, `np.eye`, `np.meshgrid`, and the `_like` family.
2. **Array Attributes**: Checking the properties of an array.
3. **Random Number Generation**: Creating arrays with `np.random.rand`, `np.random.randint`, `np.random.randn`, `np.random.uniform`, `np.random.normal`, and `np.random.choice`.
4. **Array Manipulation**: Reshaping, casting, flattening, copying, and transposing arrays.

In [1]:
import numpy as np

## 1.1 Array Creation
Here are some built-in NumPy functions to create arrays:

In [2]:
# 1. Create an array from a Python list (np.array)
arr = np.array([1, 2, 3, 4, 5])
print("np.array:\n", arr)

np.array:
 [1 2 3 4 5]


In [3]:
# 2. Array filled with zeros (np.zeros)
zeros = np.zeros((2, 3)) # 2 rows, 3 columns matrix
print("np.zeros:\n", zeros)

np.zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [4]:
# 3. Array filled with ones (np.ones)
ones = np.ones((3, 2))
print("np.ones:\n", ones)

np.ones:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]


In [5]:
# 4. Array with evenly spaced values within a given interval (np.arange)
arange = np.arange(0, 10, 2) # start=0, stop=10, step=2
print("np.arange:\n", arange)

np.arange:
 [0 2 4 6 8]


In [6]:
# 5. Array with evenly spaced numbers over a specified interval (np.linspace)
linspace = np.linspace(0, 1, 5) # 5 evenly spaced numbers from 0 to 1
print("np.linspace:\n", linspace)

np.linspace:
 [0.   0.25 0.5  0.75 1.  ]


In [7]:
# 6. Array filled with a constant value (np.full)
full_arr = np.full((2, 3), 7) # 2x3 matrix filled with 7
print("np.full:\n", full_arr)

np.full:
 [[7 7 7]
 [7 7 7]]


In [8]:
# 7. Identity matrix (np.eye)
identity = np.eye(3) # 3x3 identity matrix (1s on diagonal, 0s elsewhere)
print("np.eye:\n", identity)

np.eye:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


**The `_like` Family of Functions**

Sometimes you want to create a new array with the **same shape and data type** as an existing array. NumPy provides a family of `_like` functions for this:

In [9]:
# Reference array
reference = np.array([[1, 2, 3],
                      [4, 5, 6]])
print("Reference array (shape={}, dtype={}):\n".format(reference.shape, reference.dtype), reference)

# np.zeros_like — Same shape, filled with zeros
z = np.zeros_like(reference)
print("\nnp.zeros_like:\n", z)

# np.ones_like — Same shape, filled with ones
o = np.ones_like(reference)
print("\nnp.ones_like:\n", o)

# np.full_like — Same shape, filled with a custom value
f = np.full_like(reference, 99)
print("\nnp.full_like (fill=99):\n", f)

# np.empty_like — Same shape, uninitialized (contains whatever was in memory)
# Useful for performance when you plan to fill every element yourself.
e = np.empty_like(reference)
print("\nnp.empty_like (uninitialized):\n", e)

Reference array (shape=(2, 3), dtype=int64):
 [[1 2 3]
 [4 5 6]]

np.zeros_like:
 [[0 0 0]
 [0 0 0]]

np.ones_like:
 [[1 1 1]
 [1 1 1]]

np.full_like (fill=99):
 [[99 99 99]
 [99 99 99]]

np.empty_like (uninitialized):
 [[-9223370539106663118 -7237713255693616155        1497820589414]
 [       1497820589430                    7                   62]]


In [10]:
# 8. Coordinate Grids (np.meshgrid)
# Very useful for evaluating functions on a grid or preparing data for 2D/3D plots.
x = np.array([1, 2, 3])
y = np.array([4, 5])
X, Y = np.meshgrid(x, y)
print("X grid (repeated x):\n", X)
print("\nY grid (repeated y):\n", Y)

X grid (repeated x):
 [[1 2 3]
 [1 2 3]]

Y grid (repeated y):
 [[4 4 4]
 [5 5 5]]


## 1.2 Array Attributes
Every NumPy array has built-in attributes to check its dimensions, size, and data type.

In [11]:
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print("Matrix:\n", matrix)

print("\n--- Attributes ---")
print("Shape (rows, columns):", matrix.shape)
print("Size (total elements) :", matrix.size)
print("Ndim (number of dimensions):", matrix.ndim)
print("Dtype (data type)    :", matrix.dtype)

Matrix:
 [[1 2 3]
 [4 5 6]]

--- Attributes ---
Shape (rows, columns): (2, 3)
Size (total elements) : 6
Ndim (number of dimensions): 2
Dtype (data type)    : int64


## 1.3 Random Number Generation
Often, we need dummy data containing random numbers. The `np.random` module provides this.

In [12]:
# Random numbers from a uniform distribution [0, 1)
rand_arr = np.random.rand(2, 2)
print("Random (0-1):\n", rand_arr)

# Random integers (start, stop, size)
randint_arr = np.random.randint(0, 10, size=(3, 3))
print("\nRandom Integer (0-9):\n", randint_arr)

# Standard Normal Distribution (mean=0, std=1)
randn_arr = np.random.randn(3)
print("\nRandom Normal:\n", randn_arr)

Random (0-1):
 [[0.7452477  0.32212685]
 [0.6084121  0.90505543]]

Random Integer (0-9):
 [[0 8 3]
 [4 1 6]
 [8 0 5]]

Random Normal:
 [ 0.98418354  0.02497767 -0.63571286]


**Reproducibility (Setting a Seed)**
To get the same random numbers every time you run the code, you can set a seed.

In [13]:
np.random.seed(42) # The number 42 is arbitrary
print("Seeded random:\n", np.random.rand(2))

Seeded random:
 [0.37454012 0.95071431]


**Random Choice**
You can also pick random elements from an existing array or list.

In [14]:
choices = ["apple", "banana", "cherry", "date"]
random_choice = np.random.choice(choices, size=2, replace=False)
print("Random choice:\n", random_choice)

Random choice:
 ['banana' 'date']


**Specific Random Distributions**

Besides `np.random.rand` (uniform 0-1) and `np.random.randn` (standard normal), NumPy provides functions to generate random numbers from specific distributions with custom parameters.

In [15]:
# --- np.random.uniform ---
# Generates random floats from a uniform distribution within a specified range [low, high).
# Useful for generating random coordinates, prices, or any continuous random data.
np.random.seed(42)

# Generate 5 random temperatures between 20.0 and 35.0
random_temps = np.random.uniform(low=20.0, high=35.0, size=5)
print("Random Temperatures (20-35):", np.round(random_temps, 2))

# Generate a 3x2 matrix of random coordinates between 0 and 100
random_coords = np.random.uniform(low=0, high=100, size=(3, 2))
print("\nRandom Coordinates (0-100):\n", np.round(random_coords, 2))

Random Temperatures (20-35): [25.62 34.26 30.98 28.98 22.34]

Random Coordinates (0-100):
 [[15.6   5.81]
 [86.62 60.11]
 [70.81  2.06]]


In [16]:
# --- np.random.normal ---
# Generates random numbers from a normal (Gaussian) distribution.
# Parameters: loc=mean, scale=standard_deviation, size=shape
# This is essential for generating realistic data that follows a bell curve.
np.random.seed(42)

# Generate 5 exam scores centered around 75 with std of 10
exam_scores = np.random.normal(loc=75, scale=10, size=5)
print("Random Exam Scores (mean=75, std=10):", np.round(exam_scores, 2))

# Generate 2D points centered around [50, 50]
# This is commonly used to generate cluster data for testing algorithms.
cluster_points = np.random.normal(loc=[50, 50], scale=5, size=(4, 2))
print("\nRandom 2D Points (mean=[50,50], std=5):\n", np.round(cluster_points, 2))

Random Exam Scores (mean=75, std=10): [79.97 73.62 81.48 90.23 72.66]

Random 2D Points (mean=[50,50], std=5):
 [[48.83 57.9 ]
 [53.84 47.65]
 [52.71 47.68]
 [47.67 51.21]]


## 1.4 Array Manipulation
Two very common and essential operations are changing the shape of an array and changing its data type.

**1. Reshaping Arrays (`arr.reshape`)**
Reshaping is highly used when preparing data for **Machine Learning models** (e.g., converting a flat 1D array of pixels into a 2D image matrix).

In [17]:
# Create a 1D array with 12 elements
arr_flat = np.arange(12)
print("Original 1D array:\n", arr_flat)

# Reshape into a 2D array (3 rows, 4 columns)
# Note: The total number of elements must remain the same (3 * 4 = 12)
arr_2d = arr_flat.reshape(3, 4)
print("\nReshaped to 3x4 matrix:\n", arr_2d)

Original 1D array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped to 3x4 matrix:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


**2. Type Casting (`arr.astype`)**
Changing data types is extremely useful for **saving memory** (e.g., converting `float64` to `float32`) or when an algorithm strictly requires integers.

In [18]:
# Array of floating point numbers
arr_float = np.array([1.9, 2.5, 3.1])
print("Float array:", arr_float)
print("Data type:", arr_float.dtype)

# Cast to integers (this truncates the decimals, it does NOT round)
arr_int = arr_float.astype(int)
print("\nInteger array:", arr_int)
print("New Data type:", arr_int.dtype)

Float array: [1.9 2.5 3.1]
Data type: float64

Integer array: [1 2 3]
New Data type: int64


**3. Flattening Arrays (`arr.flatten`)**
Flattening is the opposite of reshaping. It converts a multi-dimensional array into a 1D array. This is frequently used when feeding image data or matrices into a Machine Learning model that expects a flat list of numbers.

In [19]:
# Let's use a 2D matrix
matrix_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("Original 2D Matrix:\n", matrix_2d)

# Flatten it to 1D
flat_arr = matrix_2d.flatten()
print("\nFlattened 1D Array:", flat_arr)

Original 2D Matrix:
 [[1 2 3]
 [4 5 6]]

Flattened 1D Array: [1 2 3 4 5 6]


**4. Copying Arrays (`arr.copy`)**
In NumPy, assigning an array to a new variable or slicing it often creates a **view** (a reference), NOT a new copy in memory. If you change the view, the original data changes! Using `.copy()` ensures you create a safe, independent duplicate.

In [20]:
original = np.array([10, 20, 30])

# ❌ WRONG WAY (Creates a reference / view)
reference = original
reference[0] = 99
print("Original after modifying reference:", original) # Original is modified!

# Reset the original
original = np.array([10, 20, 30])

# ✅ CORRECT WAY (Creates an independent copy)
safe_copy = original.copy()
safe_copy[0] = 99
print("\nOriginal after modifying safe copy:", original) # Original stays safe!
print("Safe copy:", safe_copy)

Original after modifying reference: [99 20 30]

Original after modifying safe copy: [10 20 30]
Safe copy: [99 20 30]


**5. Transposing Arrays (`arr.T`)**
Transposing swaps the rows and columns of an array. It is heavily used in linear algebra and preparing datasets.

In [21]:
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print("Original Matrix:\n", matrix)
print("Shape:", matrix.shape)

transposed = matrix.T
print("\nTransposed Matrix:\n", transposed)
print("New Shape:", transposed.shape)

Original Matrix:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)

Transposed Matrix:
 [[1 4]
 [2 5]
 [3 6]]
New Shape: (3, 2)
