# 2. Indexing & Slicing

In this notebook, we will learn how to access, slice, and select elements from NumPy arrays. This is crucial because in data processing, we rarely process the entire raw array at once.

We will cover:
1. **1D Array Indexing & Slicing**: Basic ways to access data.
2. **2D/3D Array Indexing & Slicing**: Working with matrices (rows & columns).
3. **Boolean Indexing (Masking)**: Filtering elements based on conditions (e.g., numbers > 5).
4. **Fancy Indexing**: Using lists/arrays of indices to select specific elements.

In [1]:
import numpy as np

## 2.1 1D Array Indexing & Slicing
Similar to built-in Python lists, NumPy arrays use zero-based indexing. Slicing uses the `[start:stop:step]` format.

In [2]:
# 1. Create a 1D array
arr_1d = np.arange(10, 20) # [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
print("Original array:\n", arr_1d)

# 2. Basic indexing
print("\nElement at index 0:", arr_1d[0])
print("Last element:", arr_1d[-1])

# 3. Slicing
print("\nFrom index 2 to 5:", arr_1d[2:6]) # 'stop' is exclusive
print("From start to index 3:", arr_1d[:4])
print("With step of 2:", arr_1d[::2])

# 4. Modifying values with slicing
arr_1d[0:2] = 99
print("\nAfter modification:\n", arr_1d)

Original array:
 [10 11 12 13 14 15 16 17 18 19]

Element at index 0: 10
Last element: 19

From index 2 to 5: [12 13 14 15]
From start to index 3: [10 11 12 13]
With step of 2: [10 12 14 16 18]

After modification:
 [99 99 12 13 14 15 16 17 18 19]


## 2.2 2D/3D Array Indexing & Slicing
For 2D arrays, we use the `[row, column]` or `[start_row:stop_row, start_col:stop_col]` format.

In [3]:
# 1. Create a 2D array
arr_2d = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 100, 110, 120]
])
print("Matrix:\n", arr_2d)

# 2. Accessing a single element (Row 1, Column 2)
print("\nElement at row index 1, col index 2:", arr_2d[1, 2]) # 70

# 3. 2D Slicing: First 2 rows, first 2 columns
print("\n2D Slicing (Top-left 2x2):\n", arr_2d[:2, :2])

# 4. Accessing an entire row
print("\nEntire row index 1:", arr_2d[1, :])

# 5. Accessing an entire column
print("Entire column index 2:", arr_2d[:, 2])

Matrix:
 [[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]

Element at row index 1, col index 2: 70

2D Slicing (Top-left 2x2):
 [[10 20]
 [50 60]]

Entire row index 1: [50 60 70 80]
Entire column index 2: [ 30  70 110]


**3D Array Indexing (e.g., Image Data)**
A 3D array can be thought of as a collection of 2D matrices (like layers). It is extremely common in Image Processing where dimensions are typically `(Channels, Height, Width)` or `(Batch, Height, Width)`.

In [4]:
# Create a 3D array: 2 layers, 3 rows, 3 columns (2, 3, 3)
arr_3d = np.array([
    [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]],

    [[10, 11, 12],
     [13, 14, 15],
     [16, 17, 18]]
])

print("3D Array Shape:", arr_3d.shape)

# 1. Accessing the second layer (index 1)
print("\nSecond Layer:\n", arr_3d[1])

# 2. Accessing a specific row in the first layer
print("\nFirst layer, second row:", arr_3d[0, 1]) # equivalent to arr_3d[0][1]

# 3. Accessing a specific single element: 2nd layer, 3rd row, 1st column (value is 16)
print("\nSpecific element:", arr_3d[1, 2, 0])

3D Array Shape: (2, 3, 3)

Second Layer:
 [[10 11 12]
 [13 14 15]
 [16 17 18]]

First layer, second row: [4 5 6]

Specific element: 16


## 2.3 Boolean Indexing (Masking)
This is one of the most frequently used NumPy features in Data Science. We can provide conditions (like `>`, `<`, `==`) to filter data.

In [5]:
# 1. Create an array
arr_bool = np.arange(1, 11)
print("Original array:\n", arr_bool)

# 2. Create a mask array (containing True/False)
mask = arr_bool > 5
print("\nMasking (arr_bool > 5):\n", mask)

# 3. Apply the mask to filter data
filtered_arr = arr_bool[mask]
print("\nElements greater than 5:\n", filtered_arr)

# 4. Shorthand (most common usage)
even_numbers = arr_bool[arr_bool % 2 == 0]
print("\nEven numbers:\n", even_numbers)

Original array:
 [ 1  2  3  4  5  6  7  8  9 10]

Masking (arr_bool > 5):
 [False False False False False  True  True  True  True  True]

Elements greater than 5:
 [ 6  7  8  9 10]

Even numbers:
 [ 2  4  6  8 10]


**Multiple Conditions (AND / OR)**
Often, you need to filter data using multiple conditions. In NumPy, you MUST use the bitwise operators `&` (AND) and `|` (OR), and you **must** wrap each condition in parentheses.

In [6]:
# Let's use our arr_bool [1 to 10] array again
print("Original array:", arr_bool)

# AND condition (&): Numbers greater than 3 AND less than 8
# Note the parentheses around each condition!
mask_and = (arr_bool > 3) & (arr_bool < 8)
print("\nNumbers > 3 AND < 8:\n", arr_bool[mask_and])

# OR condition (|): Numbers less than 3 OR greater than 8
mask_or = (arr_bool < 3) | (arr_bool > 8)
print("\nNumbers < 3 OR > 8:\n", arr_bool[mask_or])

Original array: [ 1  2  3  4  5  6  7  8  9 10]

Numbers > 3 AND < 8:
 [4 5 6 7]

Numbers < 3 OR > 8:
 [ 1  2  9 10]


**Modifying Values using Boolean Indexing**
You can also use masks to replace specific values in an array. This is extremely useful for **data cleaning**, such as removing outliers or handling invalid data.

In [7]:
# 5. Replace values based on a condition
arr_data = np.array([-1, 2, -3, 4, 5, -6])
print("Original data containing negative values:", arr_data)

# Replace all negative values with 0
arr_data[arr_data < 0] = 0
print("After replacing negatives with 0:", arr_data)

Original data containing negative values: [-1  2 -3  4  5 -6]
After replacing negatives with 0: [0 2 0 4 5 0]


**Using `np.where()`**
`np.where(condition, x, y)` is a very powerful function. It yields `x` where the condition is True, and `y` where the condition is False. It is often used to **map or categorize data** based on specific rules without using loops.

In [8]:
# 6. Using np.where() to categorize data
scores = np.array([85, 40, 90, 55, 75])
print("Original scores:", scores)

# Create a new array where scores >= 60 become "Pass", and others become "Fail"
results = np.where(scores >= 60, "Pass", "Fail")
print("Results using np.where():", results)

Original scores: [85 40 90 55 75]
Results using np.where(): ['Pass' 'Fail' 'Pass' 'Fail' 'Pass']


## 2.4 Fancy Indexing
Fancy indexing means we provide a list or an array of indices to access or rearrange specific elements.

In [9]:
# 1. Create an array
arr_fancy = np.zeros((5, 5))
for i in range(5):
    arr_fancy[i] = i
print("Original array:\n", arr_fancy)

# 2. Select rows in a specific order (row 4, then 0, then 2)
print("\nFancy indexing rows 4, 0, 2:\n", arr_fancy[[4, 0, 2]])

# 3. Useful for selecting random rows
random_indices = np.random.choice(5, 3, replace=False)
print("\nRandom rows from the array:\n", arr_fancy[random_indices])

Original array:
 [[0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4.]]

Fancy indexing rows 4, 0, 2:
 [[4. 4. 4. 4. 4.]
 [0. 0. 0. 0. 0.]
 [2. 2. 2. 2. 2.]]

Random rows from the array:
 [[4. 4. 4. 4. 4.]
 [1. 1. 1. 1. 1.]
 [3. 3. 3. 3. 3.]]
