# 3. Mathematical Operations

NumPy makes mathematical operations over large datasets incredibly fast and concise compared to standard Python loops.

We will cover:
1. **Element-wise Operations**: Basic arithmetic (+, -, *, /) applied to every element.
2. **Aggregation Functions**: Summarizing data using `sum`, `mean`, `max`, `min`, and `std`.
3. **Matrix Operations**: Mathematical operations commonly used in linear algebra, such as dot products.
4. **Universal Math Functions (ufuncs)**: Built-in fast mathematical functions.
5. **Rounding**: Techniques for rounding arrays.
6. **Argmax and Argmin**: Finding the position (index) of maximum and minimum values.
7. **Advanced Statistics**: Calculating medians and percentiles.
8. **Absolute Values**: Using `np.abs`.
9. **Value Clipping**: Restricting values to a range using `np.clip`.
10. **Cumulative Computations**: Calculating cumulative sum with `np.cumsum`.

In [12]:
import numpy as np

## 3.1 Element-wise Operations (Arithmetic)
Arithmetic operations on arrays apply to each element individually. This is highly useful for tasks like **feature scaling** or applying mathematical transformations to an entire dataset at once (e.g., converting temperatures from Celsius to Fahrenheit without a `for loop`).

In [13]:
# 1. Basic Arithmetic
arr1 = np.array([10, 20, 30])
arr2 = np.array([1, 2, 3])

print("Addition (+):", arr1 + arr2)
print("Subtraction (-):", arr1 - arr2)
print("Multiplication (*):", arr1 * arr2)
print("Division (/):", arr1 / arr2)

# 2. Operations with Scalars (Single numbers)
# Useful for applying a constant transformation, like adding a bias.
print("\nAdd 5 to everything:", arr1 + 5)
print("Square everything (**2):", arr1 ** 2)

Addition (+): [11 22 33]
Subtraction (-): [ 9 18 27]
Multiplication (*): [10 40 90]
Division (/): [10. 10. 10.]

Add 5 to everything: [15 25 35]
Square everything (**2): [100 400 900]


## 3.2 Aggregation Functions
Aggregation functions summarize data into a single value. These are essential for **statistical analysis**, finding the average of a metric, finding the maximum/minimum bounds, or calculating the standard deviation (spread of data).

In [14]:
data = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

print("Data:\n", data)
print("\nSum of all elements:", np.sum(data))
print("Mean (Average):", np.mean(data))
print("Maximum value:", np.max(data))
print("Minimum value:", np.min(data))
print("Standard Deviation:", np.std(data))

# VERY IMPORTANT: Aggregating along an axis
# axis=0 aggregates column by column (e.g., finding the average of each feature/column)
# axis=1 aggregates row by row (e.g., finding the total score of each student/row)
print("\nSum of each column (axis=0):", np.sum(data, axis=0))
print("Sum of each row (axis=1):", np.sum(data, axis=1))

Data:
 [[10 20 30]
 [40 50 60]]

Sum of all elements: 210
Mean (Average): 35.0
Maximum value: 60
Minimum value: 10
Standard Deviation: 17.07825127659933

Sum of each column (axis=0): [50 70 90]
Sum of each row (axis=1): [ 60 150]


## 3.3 Matrix Operations
These operations follow the rules of linear algebra. The **Dot Product** is particularly fundamental in **Machine Learning**, especially in Neural Networks for calculating weights and inputs.

In [15]:
matrix_A = np.array([[1, 2],
                     [3, 4]])

matrix_B = np.array([[5, 6],
                     [7, 8]])

# 1. Element-wise multiplication (NOT a dot product)
print("Element-wise multiplication:\n", matrix_A * matrix_B)

# 2. Dot Product (Matrix Multiplication)
# This is heavily used in Deep Learning layers.
dot_product = np.dot(matrix_A, matrix_B)
# Alternatively: dot_product = matrix_A @ matrix_B
print("\nDot Product:\n", dot_product)

# 3. Transpose
# Swaps rows and columns. Useful when dimensions need to align for a dot product.
print("\nTranspose of A:\n", matrix_A.T)

Element-wise multiplication:
 [[ 5 12]
 [21 32]]

Dot Product:
 [[19 22]
 [43 50]]

Transpose of A:
 [[1 3]
 [2 4]]


## 3.4 Universal Math Functions (ufuncs)
NumPy provides many universal functions that apply mathematical operations element-by-element. These are widely used for **data transformations**.

In [16]:
arr_math = np.array([1, 4, 9, 16])

print("Original array:", arr_math)
print("Square Root (np.sqrt):", np.sqrt(arr_math))

# Exponential (e^x) and Logarithm
# Highly used in statistical formulas and machine learning activation functions
arr_small = np.array([1, 2, 3])
print("\nExponential (np.exp):", np.exp(arr_small))
print("Natural Log (np.log):", np.log(arr_small))

Original array: [ 1  4  9 16]
Square Root (np.sqrt): [1. 2. 3. 4.]

Exponential (np.exp): [ 2.71828183  7.3890561  20.08553692]
Natural Log (np.log): [0.         0.69314718 1.09861229]


## 3.5 Rounding
When dealing with floating-point numbers, you often need to round them to integers or a specific number of decimal places.

In [17]:
arr_floats = np.array([1.2, 2.5, 3.8, -1.2, -2.8])
print("Original floats:", arr_floats)

print("\nStandard Rounding (np.round):", np.round(arr_floats))
print("Round Down (np.floor):", np.floor(arr_floats))
print("Round Up (np.ceil):", np.ceil(arr_floats))

Original floats: [ 1.2  2.5  3.8 -1.2 -2.8]

Standard Rounding (np.round): [ 1.  2.  4. -1. -3.]
Round Down (np.floor): [ 1.  2.  3. -2. -3.]
Round Up (np.ceil): [ 2.  3.  4. -1. -2.]


## 3.6 Argmax and Argmin
While `max()` and `min()` tell you *what* the largest/smallest value is, `argmax()` and `argmin()` tell you **where** (at what index) that value is located. This is exceptionally useful in Classification tasks to find the predicted class.

In [18]:
# Imagine these are probabilities output by a Machine Learning model for 3 classes
probabilities = np.array([0.1, 0.7, 0.2])
print("Probabilities:", probabilities)

# Which class has the highest probability?
max_val = np.max(probabilities)
predicted_class_index = np.argmax(probabilities)

print(f"\nHighest probability is {max_val}")
print(f"Located at index (Predicted Class): {predicted_class_index}")

Probabilities: [0.1 0.7 0.2]

Highest probability is 0.7
Located at index (Predicted Class): 1


## 3.7 Advanced Statistics (Median & Percentiles)
While `mean` is useful, it is highly sensitive to outliers. `median` (the middle value) and `percentile` are robust statistical tools heavily used in Data Analysis.

In [19]:
# Example: Salaries in a company (one CEO earns 1,000,000, others earn normal wages)
salaries = np.array([30000, 35000, 40000, 42000, 1000000])

print("Mean (Average) Salary:", np.mean(salaries)) # Heavily skewed by the CEO!
print("Median (Middle) Salary:", np.median(salaries)) # A much better representation

# Percentiles: 25th, 50th (median), and 75th percentiles
q1, median_val, q3 = np.percentile(salaries, [25, 50, 75])
print(f"\n25th Percentile (Q1): {q1}")
print(f"75th Percentile (Q3): {q3}")

Mean (Average) Salary: 229400.0
Median (Middle) Salary: 40000.0

25th Percentile (Q1): 35000.0
75th Percentile (Q3): 42000.0


## 3.8 Absolute Values (`np.abs`)
Returns the absolute (positive) value of elements. This is fundamentally used when calculating "distance" or "error" between predictions and actual values (e.g., Mean Absolute Error).

In [20]:
actual_prices = np.array([100, 150, 200])
predicted_prices = np.array([110, 140, 250])

# Calculate the raw errors (can be negative)
errors = actual_prices - predicted_prices
print("Raw Errors:", errors)

# Absolute errors (always positive)
abs_errors = np.abs(errors)
print("Absolute Errors:", abs_errors)

print(f"\nMean Absolute Error (MAE): {np.mean(abs_errors)}")

Raw Errors: [-10  10 -50]
Absolute Errors: [10 10 50]

Mean Absolute Error (MAE): 23.333333333333332


## 3.9 Value Clipping (`np.clip`)
`np.clip(array, min_val, max_val)` forces all values in an array to stay within a defined range. Anything below `min_val` becomes `min_val`, and anything above `max_val` becomes `max_val`.

In [21]:
# Imagine pixel values that must remain between 0 and 255
pixels = np.array([-50, 100, 200, 300])
print("Original pixels:", pixels)

# Clip the values to a valid color range [0, 255]
clipped_pixels = np.clip(pixels, 0, 255)
print("Clipped pixels:", clipped_pixels)

Original pixels: [-50 100 200 300]
Clipped pixels: [  0 100 200 255]


## 3.10 Cumulative Computations (`np.cumsum`)
`np.cumsum` returns the cumulative sum (running total) of elements along a given axis.

In [22]:
# Daily sales revenue over a 5-day week
daily_sales = np.array([100, 250, 150, 300, 200])
print("Daily Sales:", daily_sales)

# Calculate total revenue at the end of each day
running_total = np.cumsum(daily_sales)
print("Running Total (Cumulative):", running_total)

Daily Sales: [100 250 150 300 200]
Running Total (Cumulative): [ 100  350  500  800 1000]
