# 4. Broadcasting in NumPy

**Broadcasting** is one of the most powerful and unique features of NumPy. It describes how NumPy treats arrays with **different shapes** during arithmetic operations. 

Instead of writing slow `for` loops to add a small array to a large array, NumPy "broadcasts" the smaller array across the larger array so that they have compatible shapes.

We will cover:
1. **Broadcasting with Scalars**: The simplest form.
2. **The Rules of Broadcasting**: How NumPy decides if two arrays can be broadcasted.
3. **Adjusting Dimensions**: Using `np.newaxis` and `np.expand_dims`.
4. **Broadcasting Arrays of Different Shapes**: Adding 1D to 2D, and Row vectors to Column vectors.
5. **Real-world Example**: Data Normalization.

In [1]:
import numpy as np

## 4.1 Broadcasting with Scalars
You have already seen broadcasting in action! When you add, multiply, or subtract a single number (a scalar) from an array, NumPy automatically broadcasts that scalar to every element in the array.

In [2]:
arr = np.array([1, 2, 3])

# The scalar '10' is broadcasted to [10, 10, 10] behind the scenes
result = arr + 10

print("Original Array:", arr)
print("Array + 10    :", result)

Original Array: [1 2 3]
Array + 10    : [11 12 13]


## 4.2 The Rules of Broadcasting
When operating on two arrays, NumPy compares their shapes element-wise. It starts with the **trailing (rightmost) dimensions** and works its way left.

Two dimensions are **compatible** if:
1. **They are equal**, OR
2. **One of them is 1**.

If these conditions are not met, a `ValueError: operands could not be broadcast together` is thrown.

## 4.3 Adjusting Dimensions (`np.newaxis`)
Sometimes, to make arrays compatible for broadcasting, you need to add an empty dimension. This is very common when preparing data for Machine Learning models.

In [3]:
arr_1d = np.array([1, 2, 3]) # Shape: (3,)
print("Original 1D Shape:", arr_1d.shape)

# Add a new axis to make it a Column Vector (3, 1)
col_vec = arr_1d[:, np.newaxis]
# Alternatively: col_vec = np.expand_dims(arr_1d, axis=1)
print("\nColumn Vector Shape:", col_vec.shape)
print("Column Vector:\n", col_vec)

Original 1D Shape: (3,)

Column Vector Shape: (3, 1)
Column Vector:
 [[1]
 [2]
 [3]]


## 4.4 Broadcasting Arrays of Different Shapes
Let's look at a common scenario: adding a 1D array to a 2D array. This happens often when you want to add a specific "bias" or value to every row/column of a dataset.

In [4]:
# Example 1: 2D Array + 1D Array
matrix = np.array([
    [10, 20, 30],
    [40, 50, 60]
]) # Shape: (2, 3)

vector = np.array([1, 2, 3]) # Shape: (3,)

# NumPy matches the rightmost dimension (3 and 3).
# It stretches the 1D 'vector' across the 2 rows of 'matrix'.
print("Result of Matrix + Vector:\n", matrix + vector)

Result of Matrix + Vector:
 [[11 22 33]
 [41 52 63]]


In [5]:
# Example 2: Column Vector + Row Vector (Creates a Grid!)
col_vector = np.array([[10],
                       [20],
                       [30]]) # Shape: (3, 1)

row_vector = np.array([1, 2, 3]) # Shape: (3,)

# col_vector is broadcasted across columns.
# row_vector is broadcasted across rows.
grid = col_vector + row_vector

print("Column Vector Shape:", col_vector.shape)
print("Row Vector Shape   :", row_vector.shape)
print("\nResulting Grid:\n", grid)

Column Vector Shape: (3, 1)
Row Vector Shape   : (3,)

Resulting Grid:
 [[11 12 13]
 [21 22 23]
 [31 32 33]]


## 4.5 Real-world Example: Data Normalization
A very common task in Machine Learning is **centering** data (subtracting the mean of each column from the data). Broadcasting makes this a one-liner!

In [6]:
# Let's say we have 3 students (rows) and their scores in 2 subjects (columns)
scores = np.array([
    [90, 80],
    [70, 60],
    [85, 95]
]) # Shape: (3, 2)

# Step 1: Find the mean score for each subject (axis=0 calculates column means)
mean_scores = np.mean(scores, axis=0) # Shape: (2,)
print("Original Scores:\n", scores)
print("\nMean of each subject:", mean_scores)

# Step 2: Center the data using Broadcasting
# The mean_scores (1D) will be subtracted from every row in scores (2D)
centered_scores = scores - mean_scores
print("\nCentered Scores (0 mean):\n", centered_scores)

# Verification: The new means should be exactly 0 (or very close to 0)
print("\nNew Mean of Centered Data:", np.round(np.mean(centered_scores, axis=0), 5))

Original Scores:
 [[90 80]
 [70 60]
 [85 95]]

Mean of each subject: [81.66666667 78.33333333]

Centered Scores (0 mean):
 [[  8.33333333   1.66666667]
 [-11.66666667 -18.33333333]
 [  3.33333333  16.66666667]]

New Mean of Centered Data: [-0.  0.]
