# 5. Advanced Array Manipulation

Now that you have mastered the fundamentals of NumPy arrays, it's time to learn how to **manipulate** them in more powerful ways.

In real-world data science and machine learning, you constantly need to combine datasets, find specific values, sort results, or filter data based on conditions. This module gives you the tools to do all of that.

We will cover:
1. **Joining Arrays**: Combining multiple arrays into one using `np.concatenate`, `np.vstack`, and `np.hstack`.
2. **Splitting Arrays**: Breaking one array into multiple smaller arrays using `np.split`, `np.hsplit`, and `np.vsplit`.
3. **Conditional Searching**: Finding and replacing values based on conditions using `np.where`.
4. **Unique Values & Membership**: Extracting unique values and checking membership using `np.unique` and `np.isin`.
5. **Sorting Arrays**: Ordering elements using `np.sort` and `np.argsort`.
6. **Adding & Removing Elements**: Modifying array contents with `np.append`, `np.insert`, and `np.delete`.
7. **Handling Missing Values**: Detecting and dealing with `NaN` values using `np.isnan`, `np.nan_to_num`, `np.nanmean`, and `np.nansum`.
8. **Boolean Aggregation & Counting**: Summarizing boolean conditions with `np.any`, `np.all`, and `np.count_nonzero`.

In [1]:
import numpy as np

## 5.1 Joining Arrays

Joining arrays means putting two or more arrays together into a single one. NumPy provides several functions for this, each with a different behavior depending on the axis you want to join along.

In [2]:
# --- np.concatenate ---
# The most general joining function. Works along any specified axis.
arr_a = np.array([1, 2, 3])
arr_b = np.array([4, 5, 6])

# Join two 1D arrays end-to-end
joined_arr = np.concatenate((arr_a, arr_b))

print("arr_a    :", arr_a)
print("arr_b    :", arr_b)
print("concatenated:", joined_arr)

arr_a    : [1 2 3]
arr_b    : [4 5 6]
concatenated: [1 2 3 4 5 6]


In [3]:
# --- np.vstack and np.hstack ---
# These are convenient shortcuts for stacking 2D arrays.
matrix_a = np.array([[1, 2],
                     [3, 4]])

matrix_b = np.array([[5, 6],
                     [7, 8]])

# vstack: stacks row-wise (adds more rows). Think of stacking plates.
vstacked = np.vstack((matrix_a, matrix_b))

# hstack: stacks column-wise (adds more columns). Think of placing books side-by-side.
hstacked = np.hstack((matrix_a, matrix_b))

print("matrix_a:\n", matrix_a)
print("\nmatrix_b:\n", matrix_b)
print("\nnp.vstack (stack vertically / row-wise):\n", vstacked)
print("\nnp.hstack (stack horizontally / column-wise):\n", hstacked)

matrix_a:
 [[1 2]
 [3 4]]

matrix_b:
 [[5 6]
 [7 8]]

np.vstack (stack vertically / row-wise):
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

np.hstack (stack horizontally / column-wise):
 [[1 2 5 6]
 [3 4 7 8]]


## 5.2 Splitting Arrays

Splitting is the reverse of joining. You can break a single array into multiple smaller arrays. This is useful when you want to divide a dataset into training and testing sets, for example.

In [4]:
# --- np.split ---
# Splits an array into multiple sub-arrays.
data_arr = np.array([10, 20, 30, 40, 50, 60])

# Split into 3 equal parts
split_parts = np.split(data_arr, 3)

print("Original array:", data_arr)
print("\nSplit into 3 equal parts:")
for i, part in enumerate(split_parts):
    print(f"  Part {i+1}:", part)

Original array: [10 20 30 40 50 60]

Split into 3 equal parts:
  Part 1: [10 20]
  Part 2: [30 40]
  Part 3: [50 60]


In [5]:
# --- np.vsplit and np.hsplit for 2D arrays ---
grid = np.array([[ 1,  2,  3,  4],
                 [ 5,  6,  7,  8],
                 [ 9, 10, 11, 12],
                 [13, 14, 15, 16]])

# vsplit: split row-wise (splits into horizontal sections)
top_half, bottom_half = np.vsplit(grid, 2)

# hsplit: split column-wise (splits into vertical sections)
left_half, right_half = np.hsplit(grid, 2)

print("Original 2D array:\n", grid)
print("\nnp.vsplit (split row-wise into 2 parts):")
print("  Top half:\n", top_half)
print("  Bottom half:\n", bottom_half)
print("\nnp.hsplit (split column-wise into 2 parts):")
print("  Left half:\n", left_half)
print("  Right half:\n", right_half)

Original 2D array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

np.vsplit (split row-wise into 2 parts):
  Top half:
 [[1 2 3 4]
 [5 6 7 8]]
  Bottom half:
 [[ 9 10 11 12]
 [13 14 15 16]]

np.hsplit (split column-wise into 2 parts):
  Left half:
 [[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]]
  Right half:
 [[ 3  4]
 [ 7  8]
 [11 12]
 [15 16]]


## 5.3 Conditional Searching

`np.where` is one of the most powerful functions in NumPy. It works like a **vectorized if-else statement** — it evaluates a condition for every element and returns different values depending on whether the condition is `True` or `False`.

Syntax: `np.where(condition, value_if_true, value_if_false)`

In [6]:
# Example 1: Classify scores as 'Pass' or 'Fail'
scores = np.array([45, 80, 55, 90, 30, 75, 60])

# If score >= 60, label it 'Pass', otherwise 'Fail'
pass_fail = np.where(scores >= 60, 'Pass', 'Fail')

print("Original scores:", scores)
print("Pass/Fail result:", pass_fail)

Original scores: [45 80 55 90 30 75 60]
Pass/Fail result: ['Fail' 'Pass' 'Fail' 'Pass' 'Fail' 'Pass' 'Pass']


In [7]:
# Example 2: Replace all negative values with 0
temperatures = np.array([-5, 0, 10, 25, 30, -2, 18])

# If temperature < 0, set it to 0, otherwise keep the original value
adjusted_temps = np.where(temperatures < 0, 0, temperatures)

print("Temperatures  :", temperatures)
print("Adjusted temps:", adjusted_temps)

Temperatures  : [-5  0 10 25 30 -2 18]
Adjusted temps: [ 0  0 10 25 30  0 18]


## 5.4 Unique Values & Membership

When working with data, you often need to know what **distinct values** exist in an array, or check whether certain values are **present** in the data. `np.unique` and `np.isin` are the go-to functions for these tasks.

In [8]:
# --- np.unique ---
# Returns the sorted unique elements of an array.
category_data = np.array([3, 1, 2, 1, 3, 3, 2, 1, 4, 2])

unique_categories = np.unique(category_data)
print("Raw category data :", category_data)
print("Unique categories :", unique_categories)

# You can also count how many times each unique value appears
unique_vals, counts = np.unique(category_data, return_counts=True)
print("\n--- With return_counts=True ---")
print("Unique values :", unique_vals)
print("Their counts  :", counts)

Raw category data : [3 1 2 1 3 3 2 1 4 2]
Unique categories : [1 2 3 4]

--- With return_counts=True ---
Unique values : [1 2 3 4]
Their counts  : [3 3 3 1]


In [9]:
# --- np.isin ---
# Tests whether each element of an array is contained in a set of values.
# Returns a boolean mask (True/False array).
student_ids = np.array([101, 205, 308, 101, 412, 205, 101])

# Check which entries are from student 101 or 308
ids_to_find = [101, 308]
membership_mask = np.isin(student_ids, ids_to_find)

print("Student IDs   :", student_ids)
print("IDs to find   :", ids_to_find)
print("Membership mask:", membership_mask)

# Use the mask to filter the original array
print("Matching rows  :", student_ids[membership_mask])

Student IDs   : [101 205 308 101 412 205 101]
IDs to find   : [101, 308]
Membership mask: [ True False  True  True False False  True]
Matching rows  : [101 308 101 101]


## 5.5 Sorting Arrays

NumPy provides two essential sorting functions:
- **`np.sort`**: Returns a **new sorted array** (the original is unchanged).
- **`np.argsort`**: Returns the **indices** that would sort the array. This is extremely useful when you need to reorder a related array in the same order.

In [10]:
# --- np.sort ---
unsorted_arr = np.array([42, 17, 8, 99, 35, 56])

# Returns a new sorted array in ascending order
sorted_arr = np.sort(unsorted_arr)

print("Original :", unsorted_arr)
print("Sorted   :", sorted_arr)
print("Original (unchanged):", unsorted_arr)  # np.sort does NOT modify the original

Original : [42 17  8 99 35 56]
Sorted   : [ 8 17 35 42 56 99]
Original (unchanged): [42 17  8 99 35 56]


In [11]:
# --- np.argsort ---
# The real power: sort one array based on another array's order.
exam_scores = np.array([88, 45, 72, 95, 60])
student_names = np.array(['Alice', 'Bob', 'Charlie', 'Diana', 'Eve'])

# Get the indices that would sort the scores array
sort_indices = np.argsort(exam_scores)

print("Scores :", exam_scores)
print("Names  :", student_names)
print("\nSort indices (argsort):", sort_indices)

# Now use those indices to sort both arrays in the same order
print("\nNames ranked by score (lowest to highest):")
for i in sort_indices:
    print(f"  {student_names[i]:<8}: {exam_scores[i]}")

Scores : [88 45 72 95 60]
Names  : ['Alice' 'Bob' 'Charlie' 'Diana' 'Eve']

Sort indices (argsort): [1 4 2 0 3]

Names ranked by score (lowest to highest):
  Bob     : 45
  Eve     : 60
  Charlie : 72
  Alice   : 88
  Diana   : 95


## 5.6 Adding & Removing Elements

Sometimes you need to modify an array by adding new elements or removing existing ones. 

> **Important Note**: Unlike Python lists, NumPy arrays have a **fixed size**. Functions like `np.append`, `np.insert`, and `np.delete` do **not** modify the original array. They always return a **new** array. Keep this in mind to avoid memory inefficiency in loops.

In [12]:
# --- np.append ---
# Adds values to the END of an array. Always returns a 1D array.
base_arr = np.array([10, 20, 30, 40])

# Append one or multiple values
appended_arr = np.append(base_arr, [50, 60])

print("Original    :", base_arr)
print("After append:", appended_arr)
print("Original (unchanged):", base_arr)

Original    : [10 20 30 40]
After append: [10 20 30 40 50 60]
Original (unchanged): [10 20 30 40]


In [13]:
# --- np.insert ---
# Inserts values at a SPECIFIC index position.
base_arr = np.array([10, 20, 30, 40])

# Insert the value 99 before index 2 (before the element '30')
inserted_arr = np.insert(base_arr, 2, 99)

print("Original     :", base_arr)
print("After insert at index 2:", inserted_arr)

Original     : [10 20 30 40]
After insert at index 2: [10 20 99 30 40]


In [14]:
# --- np.delete ---
# Removes elements at specified index positions.
base_arr = np.array([10, 20, 30, 40, 50])

# Delete the element at index 1 (the value '20')
deleted_one = np.delete(base_arr, 1)

# Delete multiple elements at once using a list of indices
deleted_multiple = np.delete(base_arr, [0, 3])

print("Original       :", base_arr)
print("After delete index 1:", deleted_one)
print("After delete indices [0, 3]:", deleted_multiple)

Original       : [10 20 30 40 50]
After delete index 1: [10 30 40 50]
After delete indices [0, 3]: [20 30 50]


## 5.7 Handling Missing Values (NaN)

In real-world datasets, missing values are extremely common. NumPy represents a missing or undefined floating-point number as **`NaN`** (Not a Number). Knowing how to detect and handle `NaN` is a critical skill before doing any analysis.

The key functions are:
- **`np.isnan()`**: Returns a boolean mask — `True` where the value is `NaN`.
- **`np.nan_to_num()`**: Replaces `NaN` with a specified number (default: `0`).
- **`np.nanmean()`, `np.nansum()`, `np.nanmax()`**: Safe versions of aggregation functions that **ignore** `NaN` values instead of returning `NaN`.

In [15]:
# Simulate sensor data with some missing readings (NaN)
sensor_readings = np.array([1.5, np.nan, 3.2, np.nan, 5.0, 4.1, np.nan])

# --- np.isnan ---
# Detect which positions contain NaN
nan_mask = np.isnan(sensor_readings)

print("Sensor readings  :", sensor_readings)
print("NaN mask         :", nan_mask)
print("Number of NaNs   :", np.sum(nan_mask))  # True counts as 1

# Without NaN-safe functions, the result is also NaN!
print("\n--- The danger of using regular functions with NaN ---")
print("np.mean() result :", np.mean(sensor_readings))
print("np.sum() result  :", np.sum(sensor_readings))

Sensor readings  : [1.5 nan 3.2 nan 5.  4.1 nan]
NaN mask         : [False  True False  True False False  True]
Number of NaNs   : 3

--- The danger of using regular functions with NaN ---
np.mean() result : nan
np.sum() result  : nan


In [16]:
# --- Solution 1: Use NaN-safe aggregation functions ---
# These functions simply skip NaN values when computing the result.
print("--- Solution 1: NaN-safe aggregation functions ---")
print("np.nanmean() :", np.nanmean(sensor_readings))
print("np.nansum()  :", np.nansum(sensor_readings))
print("np.nanmax()  :", np.nanmax(sensor_readings))

# --- Solution 2: Replace NaN with a specific value (e.g., 0) ---
# Useful when you want to fill missing values before further computation.
filled_arr = np.nan_to_num(sensor_readings, nan=0.0)
print("\n--- Solution 2: Replace NaN with a value ---")
print("Original     :", sensor_readings)
print("nan_to_num(0):", filled_arr)

# --- Solution 3: Remove NaN entirely using boolean indexing ---
# ~nan_mask means 'NOT NaN' (invert the mask)
clean_data = sensor_readings[~np.isnan(sensor_readings)]
print("\n--- Solution 3: Filter out NaN using boolean indexing ---")
print("Clean data:", clean_data)

--- Solution 1: NaN-safe aggregation functions ---
np.nanmean() : 3.4499999999999997
np.nansum()  : 13.799999999999999
np.nanmax()  : 5.0

--- Solution 2: Replace NaN with a value ---
Original     : [1.5 nan 3.2 nan 5.  4.1 nan]
nan_to_num(0): [1.5 0.  3.2 0.  5.  4.1 0. ]

--- Solution 3: Filter out NaN using boolean indexing ---
Clean data: [1.5 3.2 5.  4.1]


## 5.8 Boolean Aggregation & Counting

When working with boolean masks (True/False arrays), you often need to ask questions like:
- "Is **any** element True?" → `np.any()`
- "Are **all** elements True?" → `np.all()`
- "**How many** elements are True?" → `np.count_nonzero()`

These are essential for data validation, edge-case handling, and quick data summaries.

In [17]:
# --- np.any and np.all ---
# np.any: Returns True if AT LEAST ONE element satisfies the condition.
# np.all: Returns True if ALL elements satisfy the condition.

exam_scores = np.array([85, 92, 45, 78, 60])
print("Exam Scores:", exam_scores)

# Did anyone fail (score < 50)?
has_failures = np.any(exam_scores < 50)
print("\nAny failures (< 50)?:", has_failures)  # True (45 < 50)

# Did everyone pass (score >= 50)?
all_passed = np.all(exam_scores >= 50)
print("All passed (>= 50)? :", all_passed)   # False (45 failed)

# --- Using with axis for 2D arrays ---
grades = np.array([[80, 90, 70],
                   [55, 40, 65],
                   [92, 88, 95]])
print("\nGrades per student:\n", grades)

# Does each student have any failing grade (< 60)?
print("Any failing grade per student (axis=1)?:", np.any(grades < 60, axis=1))

# Does each student pass all subjects (>= 60)?
print("All subjects passed per student (axis=1)?:", np.all(grades >= 60, axis=1))

Exam Scores: [85 92 45 78 60]

Any failures (< 50)?: True
All passed (>= 50)? : False

Grades per student:
 [[80 90 70]
 [55 40 65]
 [92 88 95]]
Any failing grade per student (axis=1)?: [False  True False]
All subjects passed per student (axis=1)?: [ True False  True]


In [18]:
# --- np.count_nonzero ---
# Counts the number of non-zero (or True) elements in an array.
# When combined with a boolean condition, it counts how many elements match.

temperatures = np.array([32, 28, 35, 30, 22, 38, 27, 33])
print("Temperatures:", temperatures)

# How many days were above 30 degrees?
hot_days = np.count_nonzero(temperatures > 30)
print(f"\nDays above 30°C: {hot_days}")

# How many days were in the comfortable range (25-33)?
comfortable = np.count_nonzero((temperatures >= 25) & (temperatures <= 33))
print(f"Comfortable days (25-33°C): {comfortable}")

# You can also use it with 2D arrays and axis
# Equivalent to np.sum(condition) but more readable
data_2d = np.array([[0, 1, 0],
                    [1, 1, 1],
                    [0, 0, 1]])
print(f"\nNon-zero elements per row: {np.count_nonzero(data_2d, axis=1)}")
print(f"Non-zero elements per col: {np.count_nonzero(data_2d, axis=0)}")

Temperatures: [32 28 35 30 22 38 27 33]

Days above 30°C: 4
Comfortable days (25-33°C): 5

Non-zero elements per row: [1 3 1]
Non-zero elements per col: [1 2 2]
